### ISSUE TITLE
Is it possible to render in traffic junction environment?

### ISSUE THREAD

**Issue by SHITIANYU-hue** [sisl/DICG#1]
I noticed that there is a **render** option in dicg_ce_traffic_runner.py, but it seems that this is a redundant code and cannot actually render the environment. 

https://github.com/sisl/DICG/blob/master/exp_runners/traffic/dicg_ce_traffic_runner.py#L193

**Comment by parachutel** [comment]
The render mode for traffic junction is not really a graphic interface. It is a command line string symbol animation powered by the curses package. The render option is used for evaluation mode, and it is not enabled for training. I have pushed a fix for that. Please check it out, thanks.
