### ISSUE TITLE
Seeds used in Figure 3 of the paper

### ISSUE THREAD

**Issue by RomanChiva** [sisl/DICG#4]
Hello, My name is Roman Chiva. I am a student at TU Delft in the Netherlands. Together with a group of students we are carrying out a reproducibility project of the results presented by the paper ''Deep Implicit Coordination Graphs for Multi-agent Reinforcement Learning". One of the parts we have to reproduce is Figure 3 of the paper in which the average return for test episodes for varying penalties 𝑝 averaged over 5 runs is shown. We were wondering what seeds were used for these runs. 

Regards, 
Roman Chiva

**Comment by parachutel** [comment]
Try 1 to 5
