### ISSUE TITLE
Any difference between the baseline scripts and paper description?

### ISSUE THREAD

**Issue by LXXXXR** [sisl/DICG#5]
Hi,

Thank you for sharing your wonderful work. 

I was just trying to reproduce Fig.3 from your paper and when I run `python dec_predatorprey_runner.py --penalty -1 --seed 0` using all default parameters, it gives the final average return of 68.947. It seems overly well compared to the baseline from Fig.3 in your paper and the reference results table in `README.md`. So I was wondering if there's any parameter I need to alter to get the reported results for decentralized architecture?

Thank you very much.

**Comment by rejuvyesh** [comment]
Reported results in the paper are averaged over multiple runs!

**Comment by LXXXXR** [comment]
> Reported results in the paper are averaged over multiple runs!

Thank you very much for the kind help. But it seems that the report results also contains variance. And I ran it one more time with random seed 1 and get the result of 66.9963, still way above the reported one. So I was just wondering if there is any deviations between the default parameters in the codes and the paper's setting. I tried my best but couldn’t get any luck locating it. One thing I noticed is that the dec-mlp's critic size varies from the paper's description, but I don't know whether it would give such a performance gain. So it much appreciated if I can get your help. Thanks.

**Comment by parachutel** [comment]
Comparing with the original results in the paper, I have upgraded the dec baseline to make it stronger. The performance gap between DICG and dec has therefore been shrunk. The true difference between DICG and dec lies in the total number of steps it takes to finish the task, but due to the small step cost (-0.1) the return difference is not that significant. You can try to log and visualize the number of steps instead of returns.

**Comment by LXXXXR** [comment]
> Comparing with the original results in the paper, I have upgraded the dec baseline to make it stronger. The performance gap between DICG and dec has therefore been shrunk. The true difference between DICG and dec lies in the total number of steps it takes to finish the task, but due to the small step cost (-0.1) the return difference is not that significant. You can try to log and visualize the number of steps instead of returns.

Yes, the updated version of dec baseline seems to give the performance almost as good as dicg. Thank you very much for your clarification, it helps a lot!
